### ISSUE TITLE
Install core2_tbw

### ISSUE THREAD

**Issue by Zarevok** [galperins4/core2_tbw#4]
While installing the script I receive the following segmentation fault.

Successfully installed Jinja2-2.10 MarkupSafe-1.1.0 Werkzeug-0.14.1 arkecosystem-client-0.1.1 arkecosystem-crypto-0.1.1 asn1crypto-0.24.0 base58-1.0.2 binary-helpers-0.0.4 certifi-2018.11.29 cffi-1.11.5 chardet-3.0.4 click-7.0 coincurve-11.0.0 flask-1.0.2 flask-API-1.1 idna-2.8 itsdangerous-1.1.0 psycopg2-2.7.6.1 pycparser-2.19 python-dotenv-0.10.1 requests-2.21.0 urllib3-1.24.1 wheel-0.32.3
tbw.sh: line 14: 15399 Segmentation fault      (core dumped) pip3 install -r requirements.txt

**Comment by galperins4** [comment]
investigating......
